from fpdf import FPDF
import json
import datetime

class PDFReport(FPDF):
    def header(self):
        if self.page_no() > 1:
            self.set_font('Arial', 'I', 8)
            self.cell(0, 10, 'Antigravity Unified Security Platform - Confidential', 0, 0, 'L')
            self.ln(10)

    def footer(self):
        self.set_y(-15)
        self.set_font('Arial', 'I', 8)
        self.cell(0, 10, 'Page ' + str(self.page_no()), 0, 0, 'C')

    def chapter_title(self, title):
        self.set_font('Arial', 'B', 16)
        self.set_fill_color(240, 240, 240)
        self.cell(0, 12, title, 0, 1, 'L', 1)
        self.ln(4)

    def chapter_body(self, body):
        self.set_font('Arial', '', 11)
        self.multi_cell(0, 6, body)
        self.ln()

def generate_pdf(scan_data, output_path):
    pdf = PDFReport()
    pdf.set_auto_page_break(auto=True, margin=15)
    
    # 1. Title Page
    pdf.add_page()
    pdf.set_font('Arial', 'B', 24)
    pdf.cell(0, 40, '', 0, 1) # Spacing
    pdf.cell(0, 10, 'Security Assessment Report', 0, 1, 'C')
    pdf.set_font('Arial', '', 14)
    pdf.cell(0, 10, 'Generated by Antigravity', 0, 1, 'C')
    
    pdf.ln(40)
    pdf.set_font('Arial', 'B', 12)
    pdf.cell(40, 10, 'Scan ID:', 0, 0)
    pdf.set_font('Arial', '', 12)
    pdf.cell(0, 10, str(scan_data['id']), 0, 1)
    
    pdf.set_font('Arial', 'B', 12)
    pdf.cell(40, 10, 'Target:', 0, 0)
    pdf.set_font('Arial', '', 12)
    # Extract target from result if possible, or use ID if URL
    target = "Unknown"
    result_str = scan_data.get('result')
    results = {}
    if result_str:
        try:
            results = json.loads(result_str)
            target = results.get('target', 'Unknown')
        except: pass
    pdf.cell(0, 10, target, 0, 1)

    pdf.set_font('Arial', 'B', 12)
    pdf.cell(40, 10, 'Date:', 0, 0)
    pdf.set_font('Arial', '', 12)
    pdf.cell(0, 10, str(scan_data['timestamp']), 0, 1)

    # 2. Executive Summary
    pdf.add_page()
    pdf.chapter_title('Executive Summary')
    
    vuln_count = 0
    high_sev = 0
    med_sev = 0
    
    vulnerabilities = results.get('vulnerabilities', [])
    vuln_count = len(vulnerabilities)
    for v in vulnerabilities:
        s = v.get('severity', 'Low')
        if s == 'High' or s == 'Critical': high_sev += 1
        elif s == 'Medium': med_sev += 1
        
    summary_text = (f"This report details the findings of an automated security scan performed on {target}. "
                    f"A total of {vuln_count} issues were identified.\n\n"
                    f"Critical/High Issues: {high_sev}\n"
                    f"Medium Issues: {med_sev}\n"
                    f"Low/Info Issues: {vuln_count - high_sev - med_sev}\n\n"
                    "The scan engine performed comprehensive checks including HTTP Header analysis, "
                    "HTTP Method auditing, Directory Enumeration, Basic SQL Injection testing, and XSS probe.")
    pdf.chapter_body(summary_text)

    # 3. Detailed Findings
    pdf.add_page()
    pdf.chapter_title('Detailed Findings')

    if not vulnerabilities:
        pdf.chapter_body("No vulnerabilities were detected during this scan.")
    else:
        for i, vuln in enumerate(vulnerabilities, 1):
            name = vuln.get('name', 'Unknown Issue')
            severity = vuln.get('severity', 'Low')
            description = vuln.get('description', 'No description provided.')
            
            # Color coding for severity title (Text color)
            pdf.set_font('Arial', 'B', 12)
            if severity in ['High', 'Critical']:
                pdf.set_text_color(200, 0, 0) # Red
            elif severity == 'Medium':
                pdf.set_text_color(200, 120, 0) # Orange
            else:
                pdf.set_text_color(0, 0, 0) # Black
                
            pdf.cell(0, 8, f"{i}. {name} [{severity}]", 0, 1)
            pdf.set_text_color(0, 0, 0) # Reset
            
            pdf.set_font('Arial', '', 11)
            pdf.multi_cell(0, 6, description)
            
            # Remediation (Generic for now, based on type)
            pdf.set_font('Arial', 'I', 10)
            remediation = "Remediation: Consult standard security guidelines for this issue."
            if "Header" in name:
                remediation = "Remediation: Configure your web server (Nginx/Apache) to send the missing header."
            elif "Method" in name:
                remediation = "Remediation: Disable this HTTP method in your server configuration."
            elif "SQL" in name:
                remediation = "Remediation: Ensure all user input is parameterized or sanitized. Use Prepared Statements."
            elif "XSS" in name:
                remediation = "Remediation: Encode output data and validate input using a security library."
            
            pdf.multi_cell(0, 6, remediation)
            pdf.ln(5)

    pdf.output(output_path)
